services:
  gamehubv2:
    image: ghcr.io/kvruntime/gamehubv2:prod
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env
    ports:
      - 8888:80
