name: CreateImage

on: [push]

env:
  IMAGE_NAME: ghcr.io/${{github.actor}}/gamehubv2:prod

jobs:
  create-image:
    name: create image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{env.IMAGE_NAME}}
          build-args: 
      
      # - name: Build & push image
      #   run: |
      #     echo "Login to github"
      #     docker --version
      #     echo "${{secrets.GHCR_TOKEN}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin
      #     echo "Build"
      #     docker build -f .docker/Dockerfile -t ${{ env.IMAGE_NAME}} .
      #     echo "Push"
      #     docker push ${{ env.IMAGE_NAME}}
      - name: Call render hook
        run: |
          curl ${{secrets.DEPLOY_HOOK}}